---
Name: mailchimp_sync_config
---
SilverStripe\Security\Group:
  extensions:
    - Sunnysideup\MailchimpSyncGroupAndMembers\Extensions\GroupExtension

SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\MailchimpSyncGroupAndMembers\Extensions\MemberExtension
